//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntaraWebApi.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AntaraEntities : DbContext
    {
        public AntaraEntities()
            : base("name=AntaraEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<user_master> user_master { get; set; }
        public DbSet<page_image_text_master> page_image_text_master { get; set; }
        public DbSet<page_master> page_master { get; set; }
        public DbSet<youtube_master> youtube_master { get; set; }
    }
}
