//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntaraWebApi.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class youtube_master
    {
        public System.Guid GUID { get; set; }
        public string YouTubeLink { get; set; }
        public Nullable<short> NumberOfTimeExecuted { get; set; }
        public string YouTubeText { get; set; }
    }
}
