//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntaraAPI.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class antaraEntities : DbContext
    {
        public antaraEntities()
            : base("name=antaraEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<page_image_text_master> page_image_text_master { get; set; }
        public DbSet<page_master> page_master { get; set; }
        public DbSet<user_master> user_master { get; set; }
        public DbSet<youtube_master> youtube_master { get; set; }
    
        public virtual int DeleteYouTubeUrls()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteYouTubeUrls");
        }
    
        public virtual int sp_AddNewUser(string userName, string userEmail, string userPhone, string userLocation, string firstName, string lastName, string password, Nullable<short> isAdmin, string userImage, Nullable<short> userStatus)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("userName", userName) :
                new ObjectParameter("userName", typeof(string));
    
            var userEmailParameter = userEmail != null ?
                new ObjectParameter("userEmail", userEmail) :
                new ObjectParameter("userEmail", typeof(string));
    
            var userPhoneParameter = userPhone != null ?
                new ObjectParameter("userPhone", userPhone) :
                new ObjectParameter("userPhone", typeof(string));
    
            var userLocationParameter = userLocation != null ?
                new ObjectParameter("userLocation", userLocation) :
                new ObjectParameter("userLocation", typeof(string));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("firstName", firstName) :
                new ObjectParameter("firstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("lastName", lastName) :
                new ObjectParameter("lastName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var isAdminParameter = isAdmin.HasValue ?
                new ObjectParameter("isAdmin", isAdmin) :
                new ObjectParameter("isAdmin", typeof(short));
    
            var userImageParameter = userImage != null ?
                new ObjectParameter("userImage", userImage) :
                new ObjectParameter("userImage", typeof(string));
    
            var userStatusParameter = userStatus.HasValue ?
                new ObjectParameter("userStatus", userStatus) :
                new ObjectParameter("userStatus", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AddNewUser", userNameParameter, userEmailParameter, userPhoneParameter, userLocationParameter, firstNameParameter, lastNameParameter, passwordParameter, isAdminParameter, userImageParameter, userStatusParameter);
        }
    
        public virtual int sp_DeleteUser(string guid)
        {
            var guidParameter = guid != null ?
                new ObjectParameter("guid", guid) :
                new ObjectParameter("guid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeleteUser", guidParameter);
        }
    
        public virtual ObjectResult<sp_GetAllPageImages_Result> sp_GetAllPageImages(string guid)
        {
            var guidParameter = guid != null ?
                new ObjectParameter("guid", guid) :
                new ObjectParameter("guid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetAllPageImages_Result>("sp_GetAllPageImages", guidParameter);
        }
    
        public virtual ObjectResult<sp_GetAllUsers_Result> sp_GetAllUsers(string guid)
        {
            var guidParameter = guid != null ?
                new ObjectParameter("guid", guid) :
                new ObjectParameter("guid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetAllUsers_Result>("sp_GetAllUsers", guidParameter);
        }
    
        public virtual ObjectResult<sp_GetAllYTlinks_Result> sp_GetAllYTlinks(string guid)
        {
            var guidParameter = guid != null ?
                new ObjectParameter("guid", guid) :
                new ObjectParameter("guid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetAllYTlinks_Result>("sp_GetAllYTlinks", guidParameter);
        }
    
        public virtual ObjectResult<sp_GetUsersForLogin_Result> sp_GetUsersForLogin(string userName)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("userName", userName) :
                new ObjectParameter("userName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetUsersForLogin_Result>("sp_GetUsersForLogin", userNameParameter);
        }
    
        public virtual int sp_UpdateUser(string guid, string userName, string userEmail, string userPhone, string userLocation, string firstName, string lastName, string password, Nullable<short> isAdmin, Nullable<short> userStatus)
        {
            var guidParameter = guid != null ?
                new ObjectParameter("guid", guid) :
                new ObjectParameter("guid", typeof(string));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("userName", userName) :
                new ObjectParameter("userName", typeof(string));
    
            var userEmailParameter = userEmail != null ?
                new ObjectParameter("userEmail", userEmail) :
                new ObjectParameter("userEmail", typeof(string));
    
            var userPhoneParameter = userPhone != null ?
                new ObjectParameter("userPhone", userPhone) :
                new ObjectParameter("userPhone", typeof(string));
    
            var userLocationParameter = userLocation != null ?
                new ObjectParameter("userLocation", userLocation) :
                new ObjectParameter("userLocation", typeof(string));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("firstName", firstName) :
                new ObjectParameter("firstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("lastName", lastName) :
                new ObjectParameter("lastName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var isAdminParameter = isAdmin.HasValue ?
                new ObjectParameter("isAdmin", isAdmin) :
                new ObjectParameter("isAdmin", typeof(short));
    
            var userStatusParameter = userStatus.HasValue ?
                new ObjectParameter("userStatus", userStatus) :
                new ObjectParameter("userStatus", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateUser", guidParameter, userNameParameter, userEmailParameter, userPhoneParameter, userLocationParameter, firstNameParameter, lastNameParameter, passwordParameter, isAdminParameter, userStatusParameter);
        }
    
        public virtual int UpdateYouTubeUrls(string youTubeLink, Nullable<short> numberOfTimeExecuted, string youTubeText)
        {
            var youTubeLinkParameter = youTubeLink != null ?
                new ObjectParameter("YouTubeLink", youTubeLink) :
                new ObjectParameter("YouTubeLink", typeof(string));
    
            var numberOfTimeExecutedParameter = numberOfTimeExecuted.HasValue ?
                new ObjectParameter("NumberOfTimeExecuted", numberOfTimeExecuted) :
                new ObjectParameter("NumberOfTimeExecuted", typeof(short));
    
            var youTubeTextParameter = youTubeText != null ?
                new ObjectParameter("YouTubeText", youTubeText) :
                new ObjectParameter("YouTubeText", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateYouTubeUrls", youTubeLinkParameter, numberOfTimeExecutedParameter, youTubeTextParameter);
        }
    }
}
