//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntaraAPI.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class page_image_text_master
    {
        public string GUID { get; set; }
        public string PageId { get; set; }
        public string ImageUrl { get; set; }
        public string ImageText { get; set; }
        public string ImageControl { get; set; }
        public string LabelControl { get; set; }
        public string Description { get; set; }
    }
}
